nameOverride:
metadata:
  environment: local
image:
  tag: michelesr/puma-sinatra-example:pg
  pullPolicy: IfNotPresent
env:
  DB_USER: postgres
  DB_HOST: db
  DB_PASSWORD: app
  DB_NAME: hello
service:
  type: ClusterIP
  annotations:
    foo: bar
    hello: world
ingress:
  hostname: hello.test
  annotations:
    kubernetes.io/ingress.class: nginx
  redirectHttpToHttps: false
  paths:
    - path: /
      backend:
        serviceName: hello
        servicePort: 3000
postgresql:
  enabled: true
  persistence:
    enabled: false
  postgresqlUsername: postgres
  postgresqlPassword: app
  postgresqlDatabase: hello
  fullnameOverride: db
