nameOverride:
metadata:
  environment: local
image:
  tag: michelesr/puma-sinatra-example
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  annotations:
    foo: bar
    hello: world
ingress:
  hostname: hello.world
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  redirectHttpToHttps: false
  paths:
    - path: /*
      backend:
        serviceName: hello
        servicePort: 3000


