apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  labels:
    app: {{ template "hello.name" . }}
    env: {{ .Values.metadata.environment }}
    component: web
    chart: {{ template "hello.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
{{- if .Values.ingress.paths }}
{{ toYaml .Values.ingress.paths | indent 8 }}
{{- end }}
{{- if .Values.ingress.redirectHttpToHttps }}
        - path: /*
          backend:
            serviceName: ssl-redirect
            servicePort: use-annotation
{{- end }}
