apiVersion: v1
kind: Service
metadata:
  name: {{ template "hello.name" . }}
  labels:
    app: {{ template "hello.name" . }}
    env: {{ .Values.metadata.environment }}
    component: web
    chart: {{ template "hello.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
  externalTrafficPolicy: Cluster
  {{- end }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: {{ template "hello.name" . }}
    env: {{ .Values.metadata.environment }}
    component: web
